//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuckTorrentDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public string UserName { get; set; }
        public string IP { get; set; }
        public string FIleName { get; set; }
        public long FileSize { get; set; }
        public int Port { get; set; }
    }
}
